#!/bin/bash
if [ "$1" == "webapi" ] ; then
    poetry run uvicorn fajabot.rest.main:app --host 0.0.0.0 --port 8000 --reload
elif [ "$1" == "ttvbot" ] ; then
    poetry run python run.py
else
    /bin/sh -c $*
fi
